# Generated by Django 5.1.1 on 2024-10-07 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 20, 10, 0, 47110, tzinfo=datetime.timezone.utc)),
        ),
    ]
